site_name: "Aurae Runtime"
site_url: ""
repo_url: "https://github.com/aurae-runtime/aurae"

nav:
  - Home: index.md
  - Whitepaper: https://docs.google.com/document/d/1dA591eipsgWeAlaSwbYNQtAQaES243IIqXPAfKhJSjU/edit#
  - Aurae: https://github.com/aurae-runtime/aurae
  - Auraed: https://github.com/aurae-runtime/auraed
  - API: https://github.com/aurae-runtime/api
  - Scripts: https://github.com/aurae-runtime/scripts




theme:
  name: material
  language: en
  palette:
    scheme: slate

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
